# Numpy Operations

In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [5]:
arr - 3

array([-3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [6]:
arr + arr #arr should be same shape

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [7]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [8]:
arr / arr

<ipython-input-8-7f952cd3e0ce>:1: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [9]:
1 / 0

ZeroDivisionError: division by zero

In [10]:
1 / arr

<ipython-input-10-e66ae8057bc3>:1: RuntimeWarning: divide by zero encountered in divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [11]:
np.log(arr)

<ipython-input-11-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [12]:
arr.sum()

55

In [14]:
arr.mean()

5.0

In [16]:
arr.max()

10

In [17]:
arr_2d = np.arange(0,25).reshape(5,5)

In [18]:
arr_2d.sum(axis = 0) #accross the rows

array([50, 55, 60, 65, 70])

In [19]:
arr_2d.sum(axis = 1)

array([ 10,  35,  60,  85, 110])