# NumPy Arrays - Indexing and Selection

In [2]:
import numpy as np

In [3]:
arr = np.arange(0,11)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr[8]

8

In [6]:
arr[1:5] #index 5 is exclusive while 1 is inclusive

array([1, 2, 3, 4])

In [7]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [8]:
arr[:5]

array([0, 1, 2, 3, 4])

In [9]:
#broadcasting ----> how numpy is better than jsut python lists

arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [10]:
arr = np.arange(0,11)

In [11]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
arr_copy = arr.copy()

In [13]:
arr_copy[:5] = 99

In [14]:
arr_copy

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [15]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
# indexing on arrray or matrices

arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [17]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [18]:
arr_2d.shape

(3, 3)

In [19]:
arr_2d[1,1]

25

In [21]:
arr_2d[1][1]

25

In [20]:
arr_2d[1]

array([20, 25, 30])

In [22]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [23]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [32]:
#conditional selection

arr = np.arange(1,11)

In [33]:
bool_arr = arr>4

In [34]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [35]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [36]:
arr[arr > 4]

array([ 5,  6,  7,  8,  9, 10])

In [40]:
import numpy as np
dice_rolls = np.array([3, 1, 5, 2, 5, 1, 1, 5, 1, 4, 2, 1, 4, 5, 3, 4, 5, 2, 4, 2, 6, 6, 3, 6, 2, 3, 5, 6, 5])

total_rolls_over_two = dice_rolls[dice_rolls > 2]

In [41]:
total_rolls_over_two

array([3, 5, 5, 5, 4, 4, 5, 3, 4, 5, 4, 6, 6, 3, 6, 3, 5, 6, 5])

In [43]:
len(total_rolls_over_two)

19