# NumPy Arrays Basic Functions



In [26]:
import numpy as np

In [2]:
# converting a list to numpy array
mylist = [1,2,3]
type(mylist)

list

In [3]:
np.array(mylist)

array([1, 2, 3])

In [6]:
#built-in methods(popular)
#***np.arange***

np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0,50,2) #start at 0, stop at 50, with step size of 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])

In [8]:
#***np.zeros***
np.zeros(5) #1D vector

array([0., 0., 0., 0., 0.])

In [10]:
np.zeros((5,5)) #2D vector

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
#***np.ones***
np.ones(5)

array([1., 1., 1., 1., 1.])

In [12]:
#***np.linspace

np.linspace(0,10,3) #start at 0, stop at 10, with 3 evenly spaced points

array([ 0.,  5., 10.])

In [13]:
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [14]:
len(np.linspace(0,10,11))

11

In [16]:
#***np.eye*** creates an identity matrix

np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [18]:
#***np.random.rand*** ----> gives the number between 0 and 1 where zero is not included while 1 is
#all the numbers are in uniform distribution which means all have equal likelyhood to be an output
np.random.rand(1)

array([0.27588368])

In [20]:
np.random.rand(5,2)

array([[0.46225937, 0.97183047],
       [0.90616623, 0.70189815],
       [0.35789454, 0.18351128],
       [0.33188074, 0.2481142 ],
       [0.91457847, 0.61100473]])

In [21]:
#***np.random.randn***

np.random.randn(5)

array([-0.31955486, -0.42719507, -0.79063639, -0.25371745,  0.30191086])

In [24]:
#***np.tandom.randint*** ----> lower number is inclusive here and higher is exclusive

np.random.randint(0,101,5)

array([39, 87, 81, 32,  2])

In [25]:
#***np.random.seed***
#In NumPy, the numpy.random.seed() function sets the seed for generating random numbers.
#This allows the user to specify a value that will ensure the same sequence of random
#numbers is generated each time the code is run. This is known as deterministic behavior
#and allows for reproducibility.

np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [48]:
arr = np.arange(0,25)

In [49]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [52]:
#functions performed on array

arr1= arr.reshape(5,5)
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [53]:
arr.shape
arr1.shape

(5, 5)

In [31]:
ranarr = np.random.randint(0,101,10)

In [32]:
ranarr

array([82, 86, 74, 74, 87, 99, 23,  2, 21, 52])

In [33]:
ranarr.max()

99

In [34]:
ranarr.min()

2

In [36]:
ranarr.argmax() #----> gives the index of the max number

5

In [37]:
ranarr.argmin()

7

In [38]:
ranarr.dtype

dtype('int64')